# Generated by Django 3.1.2 on 2020-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productitem', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='equivalent_products',
            field=models.ManyToManyField(to='productitem.Item'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_total',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
