# Generated by Django 3.1.2 on 2020-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_total',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
