# Generated by Django 3.1.2 on 2020-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productitem', '0001_initial'),
        ('recipes', '0002_auto_20201112_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='equivalent_products',
            field=models.ManyToManyField(blank=True, to='productitem.Item'),
        ),
    ]
