# Generated by Django 3.1.2 on 2020-11-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201112_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='equivalent_products',
            new_name='equivalent_product',
        ),
    ]
