# Generated by Django 3.1.2 on 2020-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_recipe_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_total',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20),
        ),
    ]
