# Generated by Django 3.1.2 on 2020-11-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201130_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
