# Generated by Django 3.1.2 on 2020-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201202_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cost_per_serving',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sort_coefficient',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
