# Generated by Django 3.1.2 on 2020-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20201202_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_NumServings',
            field=models.IntegerField(),
        ),
    ]
