# Generated by Django 3.1.2 on 2021-01-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cleaned_product_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='product_photo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
