# Generated by Django 3.1.2 on 2020-12-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productitem', '0002_auto_20201203_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_price',
            field=models.CharField(max_length=255),
        ),
    ]
